
- name: download java
  package:
    name: "{{item}}"
    state: present
  loop:
    # - epel-release
    - java 
  
- name: download tomcat 
  unarchive:
    src: "{{tomcat_url}}"
    dest: "{{tomcat_dir}}"
    remote_src: True

# - name: copy context.xml 
#   # become: yes
#   template:
#     src: "context.xml"
#     dest: "{{tomcat_dir}}/conf/context.xml"
#     force: yes

- name: copy war file
  get_url:
    url: https://tomcat-bucket-war.s3.amazonaws.com/studentapp-2.2-SNAPSHOT.war
    dest: "{{tomcat_dir}}/webapps"

- name: rename
  command: mv /{{tomcat_dir}}/webapps/studentapp-2.2-SNAPSHOT /{{tomcat_dir}}/webapps/studentapp
  ignore_errors: true

- name: start Tomcat
  shell: "nohup {{tomcat_dir}}/bin/catalina.sh start"